# Generated by Django 4.2.7 on 2023-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='Чем пользователь должен себя вознаградить после выполнения', max_length=100, null=True, verbose_name='вознаграждение'),
        ),
    ]
